<a href="https://colab.research.google.com/github/minit88/ML-DL/blob/main/Lab-01/tensor_manipulation1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import torch

# **1D Array with Numpy**

In [3]:
t =np.array([0.,1.,2.,3.,4.,5.,6.]) # 1D 
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [4]:
print('Rank of t:', t.ndim) 
print('Shape of t:', t.shape) 

Rank of t: 1
Shape of t: (7,)


In [5]:
print(' t[0] t[1] t[-1]]=',t[0],t[1],t[-1]) 
print(' t[2:5] t[4:-1]=',t[2:5],t[4:-1]) 


 t[0] t[1] t[-1]]= 0.0 1.0 6.0
 t[2:5] t[4:-1]= [2. 3. 4.] [4. 5.]


# **2D Array with NumPy**

In [6]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]]) # 2D
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [7]:
print('Rank of t:',t.ndim) 
print('Shape of t:',t.shape) # x,y

Rank of t: 2
Shape of t: (4, 3)


# **1D Array with PyTorch**

In [8]:
t= torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [9]:
print(t.dim()) # Rank
print(t.shape) # Shape
print(t.size()) # Shape
print(t[0],t[1],t[-1]) # Element
print(t[2:5],t[4:-1]) # Slicing
print(t[:2],t[3:]) # Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


# **2D Array with PyTorch**


In [11]:
t=torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [12]:
print(t.dim()) # rank
print(t.size()) # shape
print(t[:-1]) 
print(t[:,1].size())
print(t[:,:-1]) # x는 처음부터 끝 y는 처음부터 끝을 제외까지

2
torch.Size([4, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


# **Broadcasting**

In [13]:
# same shape
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [14]:
# vector + scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3]) # 3-> [[3,3]]
print(m1+m2)

tensor([[4., 5.]])


In [19]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


# **Mul vs. Matmul**

In [22]:
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))


-------------
Mul vs Matmul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


# **Mean**

In [23]:
t= torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [24]:
# Can't use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [25]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [26]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


# **Max and Argmax**

In [27]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [28]:
print(t.max()) # 4개 중에서 가장 큰 원소


tensor(4.)


In [29]:
print(t.max(dim=0)) # Returns two values: max and argmax
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [30]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


# **View**

In [31]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]]) 
ft = torch.FloatTensor(t)
print(ft.shape) # 2 x 2 x 3

torch.Size([2, 2, 3])


In [32]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [33]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


# **Squeeze**

In [34]:
ft = torch.FloatTensor([[0], [1], [2]]) 
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [35]:
print(ft.squeeze()) # 3 x 1 -> 3
print(ft.squeeze().shape)  

# ft.squeeze(dim = 0) -> 변화가 없음
# ft.squeeze(dim = 1) -> 위와 같은 동작을 수행

tensor([0., 1., 2.])
torch.Size([3])


# **Unsqueeze**

In [36]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [37]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape) # 3 -> 1 x 3

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [38]:
print(ft.view(1, -1)) # 첫번 째 차원은 1 두번째는 상관 x
print(ft.view(1, -1).shape) # 3-> 1 x 3

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [39]:
print(ft.unsqueeze(1)) # 3-> 3 x 1
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [40]:
print(ft.unsqueeze(-1)) # 3-> 3 x 1
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


# **Casting**

In [41]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [42]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [43]:
bt = torch.ByteTensor([True,False,False,True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [44]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


# **Concatenate**

In [48]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [49]:
print(torch.cat([x,y],dim=0)) # dim 0 에 맞춤춤
print(torch.cat([x,y],dim = 1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


# **Stacking**

In [50]:
x = torch.FloatTensor([1, 4]) # 2
y = torch.FloatTensor([2, 5]) # 2
z = torch.FloatTensor([3, 6]) # 2

In [51]:
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z],dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [52]:
# (1,2) (1,2) (1,2) 를 dim 0 에 쌓음
print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)],dim=0))


tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


# **Ones and Zeros** 

In [53]:
x= torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [54]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [55]:
x = torch.FloatTensor([[1,2],[3,4]])

# **In-place Operation**

In [56]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
